export const REQUEST_BREEDS_PENDING = 'REQUEST_BREEDS_PENDING';
export const REQUEST_BREEDS_SUCCESS = 'REQUEST_BREEDS_SUCCESS';
export const REQUEST_BREEDS_FAIL = 'REQUEST_BREEDS_FAIL';

export const CHANGE_BREED = 'CHANGE_BREED';

export const SELECT_BREED_PENDING = 'SELECT_BREED_PENDING';
export const SELECT_BREED_SUCCESS = 'SELECT_BREED_SUCCESS';
export const SELECT_BREED_FAIL = 'SELECT_BREED_FAIL';