export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_PRESIDENTS_PENDING  = 'REQUEST_PRESIDENTS_PENDING';
export const REQUEST_PRESIDENTS_SUCCESS  = 'REQUEST_PRESIDENTS_SUCCESS';
export const REQUEST_PRESIDENTS_FAIL  = 'REQUEST_PRESIDENTS_FAIL';

export const CHANGE_PARTY = 'CHANGE_PARTY';
